"""Predefined category bundles for multi-term scraping."""

CATEGORY_BUNDLES = {
    "baubranche": {
        "name": "Baubranche (Construction Industry)",
        "queries": [
            "Bauunternehmen",
            "Dachdecker",
            "Zimmerei",
            "Maurer",
            "Elektriker",
            "Sanitär Heizung",
            "Klempner Installateur",
            "Maler",
            "Fliesenleger",
            "Trockenbau",
            "Gerüstbau",
            "Estrich Bodenleger",
            "Straßenbau Tiefbau",
            "Schreiner Tischler",
            "Garten- und Landschaftsbau",
        ],
    },
    "baubranche_full": {
        "name": "Baubranche Full (32 terms)",
        "queries": [
            # Core Construction
            "Bauunternehmen",
            "Generalunternehmer",
            "Hochbau",
            "Tiefbau",
            "Straßenbau",
            "Abbruchunternehmen",
            # Building Envelope & Structure
            "Dachdecker",
            "Zimmerei",
            "Maurer",
            "Betonbau",
            "Gerüstbau",
            "Trockenbau",
            "Estrich",
            # Building Services (Haustechnik)
            "Elektriker",
            "Sanitär Heizung Klima",
            "Klempner",
            "Installateur",
            "Heizungsbauer",
            "Klimatechnik",
            # Finishing Trades
            "Maler",
            "Fliesenleger",
            "Bodenleger",
            "Stuckateur",
            "Glaser",
            "Schreiner",
            "Tischler",
            # Specialized & Supply
            "Baustoffe",
            "Baumarkt",
            "Fenster Türen Montage",
            "Garten- und Landschaftsbau",
            "Pflasterbau",
            "Aufzug Montage",
        ],
    },
    "baubranche_max": {
        "name": "Baubranche Maximum (50 terms)",
        "queries": [
            # Core Construction
            "Bauunternehmen",
            "Generalunternehmer",
            "Hochbau",
            "Tiefbau",
            "Straßenbau",
            "Abbruchunternehmen",
            # Building Envelope & Structure
            "Dachdecker",
            "Zimmerei",
            "Maurer",
            "Betonbau",
            "Gerüstbau",
            "Trockenbau",
            "Estrich",
            "Holzbau",
            "Stahlbau",
            "Fassadenbau",
            # Building Services (Haustechnik)
            "Elektriker",
            "Elektroinstallation",
            "Sanitär Heizung Klima",
            "Klempner",
            "Installateur",
            "Heizungsbauer",
            "Klimatechnik",
            "Lüftungsbau",
            "Spengler",
            # Finishing Trades
            "Maler",
            "Fliesenleger",
            "Bodenleger",
            "Stuckateur",
            "Glaser",
            "Schreiner",
            "Tischler",
            "Metallbau",
            "Natursteinarbeiten",
            # Specialized Construction
            "Baustoffe",
            "Baumarkt",
            "Fenster Türen Montage",
            "Garten- und Landschaftsbau",
            "Pflasterbau",
            "Aufzug Montage",
            "Erdbau Baggerarbeiten",
            "Kanalbau",
            "Containerdienst",
            "Wärmedämmung Isolierung",
            "Brandschutz",
            "Rollladenbau Sonnenschutz",
            # Modern / Renovation
            "Photovoltaik Solaranlage",
            "Badrenovierung",
            "Poolbau",
            "Wintergarten",
            "Zaunbau",
            "Baumaschinenverleih",
        ],
    },
    "seo_agencies": {
        "name": "SEO/Content/Marketing Agencies (Scaile ICP)",
        "queries": [
            # High-intent / exact ICP
            "SEO Agentur",
            "SEO Agentur für Unternehmen",
            "Content Marketing Agentur",
            "Online Marketing Agentur",
            # Broader but still relevant
            "Digital Marketing Agentur",
            "Performance Marketing Agentur",
            "Inbound Marketing Agentur",
            # Niche / high-quality leads
            "SEO Beratung",
            "SEO Freelancer",
            "Content Agentur",
            "Textagentur SEO",
        ],
    },
    "seo_agencies_en": {
        "name": "SEO & Digital Marketing Agencies EN (15 terms)",
        "queries": [
            # Core SEO — these terms catch self-described SEO businesses
            "SEO agency",
            "SEO company",
            "SEO services",
            "SEO consultant",
            # GBP category + digital marketing
            "Internet marketing service",
            "digital marketing agency",
            "marketing agency",
            "marketing consultant",
            # Adjacent — these catch agencies that also do SEO
            "web design agency",
            "PPC agency",
            "social media agency",
            "content marketing agency",
            # Broader — unique businesses not in above
            "lead generation agency",
            "PR agency",
            "creative agency",
        ],
    },
    "seo_agencies_en_max": {
        "name": "SEO & Digital Marketing Agencies EN MAX (30 terms)",
        "queries": [
            # Core SEO
            "SEO agency",
            "SEO company",
            "SEO services",
            "SEO consultant",
            "SEO specialist",
            # GBP categories & marketing
            "Internet marketing service",
            "digital marketing agency",
            "marketing agency",
            "marketing consultant",
            "online marketing agency",
            "performance marketing agency",
            # Adjacent high-value
            "web design agency",
            "web development agency",
            "PPC agency",
            "Google Ads agency",
            "social media agency",
            "content marketing agency",
            "email marketing agency",
            # Broader agency types
            "lead generation agency",
            "PR agency",
            "digital PR agency",
            "creative agency",
            "branding agency",
            "advertising agency",
            "digital agency",
            # Niche / specialist
            "growth marketing agency",
            "B2B marketing agency",
            "ecommerce marketing agency",
            "search marketing agency",
            "inbound marketing agency",
            "copywriting agency",
        ],
    },
    "dental": {
        "name": "Dental & Dentists",
        "queries": ["Zahnarzt", "Zahnklinik", "Zahnarztpraxis"],
    },
    "marketing": {
        "name": "Marketing & Advertising",
        "queries": ["Werbeagentur", "Marketingagentur", "Online Marketing Agentur"],
    },
    "legal": {
        "name": "Legal & Lawyers",
        "queries": ["Rechtsanwalt", "Anwaltskanzlei", "Notar"],
    },
    "medical": {
        "name": "Medical & Healthcare",
        "queries": ["Arzt", "Arztpraxis", "Klinik", "Facharzt"],
    },
    "real_estate": {
        "name": "Real Estate",
        "queries": ["Immobilienmakler", "Immobilienbüro", "Hausverwaltung"],
    },
}
