"""Predefined category bundles for multi-term scraping."""

CATEGORY_BUNDLES = {
    # ── German SMB Niches ──────────────────────────────────────
    "dental_de": {
        "name": "Zahnärzte (Dentists DE)",
        "queries": [
            "Zahnarzt",
            "Zahnklinik",
            "Zahnarztpraxis",
            "Kieferorthopäde",
            "Zahnimplantate",
            "Oralchirurg",
        ],
    },
    "legal_de": {
        "name": "Rechtsanwälte (Lawyers DE)",
        "queries": [
            "Rechtsanwalt",
            "Anwaltskanzlei",
            "Notar",
            "Fachanwalt",
            "Rechtsberatung",
            "Steuerberater Rechtsanwalt",
        ],
    },
    "tax_de": {
        "name": "Steuerberater (Tax Advisors DE)",
        "queries": [
            "Steuerberater",
            "Steuerkanzlei",
            "Steuerberatung",
            "Buchhalter",
            "Lohnbüro",
            "Wirtschaftsprüfer",
        ],
    },
    "medical_de": {
        "name": "Ärzte & Praxen (Doctors DE)",
        "queries": [
            "Arzt",
            "Arztpraxis",
            "Hausarzt",
            "Facharzt",
            "Orthopäde",
            "HNO Arzt",
            "Augenarzt",
            "Hautarzt",
            "Kinderarzt",
            "Internist",
        ],
    },
    "physio_de": {
        "name": "Physiotherapie (Physiotherapy DE)",
        "queries": [
            "Physiotherapie",
            "Krankengymnastik",
            "Physiotherapeut",
            "Massage Praxis",
            "Osteopathie",
            "Chiropraktiker",
        ],
    },
    "real_estate_de": {
        "name": "Immobilien (Real Estate DE)",
        "queries": [
            "Immobilienmakler",
            "Immobilienbüro",
            "Hausverwaltung",
            "Immobilienverwaltung",
            "Immobilienbewertung",
            "Immobilienberater",
        ],
    },
    "hairdresser_de": {
        "name": "Friseure (Hairdressers DE)",
        "queries": [
            "Friseur",
            "Friseursalon",
            "Frisör",
            "Barbershop",
            "Hairstylist",
            "Damenfriseur",
        ],
    },
    "restaurant_de": {
        "name": "Gastronomie (Restaurants DE)",
        "queries": [
            "Restaurant",
            "Gaststätte",
            "Imbiss",
            "Bistro",
            "Pizzeria",
            "Café",
            "Biergarten",
            "Metzgerei",
            "Bäckerei",
        ],
    },
    "auto_de": {
        "name": "KFZ & Autowerkstätten (Auto Repair DE)",
        "queries": [
            "Autowerkstatt",
            "KFZ Werkstatt",
            "Autohaus",
            "Reifenservice",
            "Autolackiererei",
            "TÜV Prüfstelle",
            "Autoaufbereitung",
            "Autoglas",
        ],
    },
    "cleaning_de": {
        "name": "Reinigung (Cleaning DE)",
        "queries": [
            "Gebäudereinigung",
            "Reinigungsfirma",
            "Glasreinigung",
            "Teppichreinigung",
            "Haushaltsreinigung",
            "Industriereinigung",
        ],
    },
    "it_de": {
        "name": "IT & EDV Dienstleister (IT Services DE)",
        "queries": [
            "IT Dienstleister",
            "EDV Service",
            "Webdesign Agentur",
            "IT Beratung",
            "Softwareentwicklung",
            "Computerservice",
            "IT Support",
        ],
    },
    "fitness_de": {
        "name": "Fitness & Sport (Fitness DE)",
        "queries": [
            "Fitnessstudio",
            "Sportstudio",
            "Yoga Studio",
            "Pilates",
            "Personal Trainer",
            "Kampfsportschule",
            "CrossFit",
        ],
    },
    "handwerk_de": {
        "name": "Handwerker allgemein (Tradespeople DE)",
        "queries": [
            "Handwerker",
            "Schlüsseldienst",
            "Schädlingsbekämpfung",
            "Umzugsunternehmen",
            "Entrümpelung",
            "Hausmeisterservice",
            "Raumausstatter",
        ],
    },
    "beauty_de": {
        "name": "Kosmetik & Beauty (Beauty DE)",
        "queries": [
            "Kosmetikstudio",
            "Nagelstudio",
            "Tattoo Studio",
            "Permanent Makeup",
            "Waxing Studio",
            "Schönheitssalon",
        ],
    },
    "baubranche": {
        "name": "Baubranche (Construction DE)",
        "queries": [
            "Bauunternehmen",
            "Dachdecker",
            "Zimmerei",
            "Maurer",
            "Elektriker",
            "Sanitär Heizung",
            "Klempner Installateur",
            "Maler",
            "Fliesenleger",
            "Trockenbau",
            "Gerüstbau",
            "Estrich Bodenleger",
            "Straßenbau Tiefbau",
            "Schreiner Tischler",
            "Garten- und Landschaftsbau",
        ],
    },
    "baubranche_full": {
        "name": "Baubranche Erweitert (Construction+ DE, 32 terms)",
        "queries": [
            "Bauunternehmen",
            "Generalunternehmer",
            "Hochbau",
            "Tiefbau",
            "Straßenbau",
            "Abbruchunternehmen",
            "Dachdecker",
            "Zimmerei",
            "Maurer",
            "Betonbau",
            "Gerüstbau",
            "Trockenbau",
            "Estrich",
            "Elektriker",
            "Sanitär Heizung Klima",
            "Klempner",
            "Installateur",
            "Heizungsbauer",
            "Klimatechnik",
            "Maler",
            "Fliesenleger",
            "Bodenleger",
            "Stuckateur",
            "Glaser",
            "Schreiner",
            "Tischler",
            "Baustoffe",
            "Fenster Türen Montage",
            "Garten- und Landschaftsbau",
            "Pflasterbau",
        ],
    },
    "marketing_de": {
        "name": "Marketing & Werbung (Marketing DE)",
        "queries": [
            "Werbeagentur",
            "Marketingagentur",
            "Online Marketing Agentur",
            "SEO Agentur",
            "Social Media Agentur",
            "Grafikdesign",
            "Druckerei",
            "Werbefilm Produktion",
        ],
    },
    "insurance_de": {
        "name": "Versicherungen (Insurance DE)",
        "queries": [
            "Versicherungsmakler",
            "Versicherungsagentur",
            "Versicherungsberater",
            "Finanzberater",
            "Allianz Vertretung",
            "Versicherungsbüro",
        ],
    },
    "photo_de": {
        "name": "Fotografie (Photography DE)",
        "queries": [
            "Fotograf",
            "Fotostudio",
            "Hochzeitsfotograf",
            "Businessfotografie",
            "Produktfotografie",
            "Videograf",
        ],
    },
    "education_de": {
        "name": "Bildung & Nachhilfe (Education DE)",
        "queries": [
            "Nachhilfe",
            "Sprachschule",
            "Fahrschule",
            "Musikschule",
            "Tanzschule",
            "Weiterbildung",
            "Coaching",
        ],
    },
    # ── English International Niches ───────────────────────────
    "dental_en": {
        "name": "Dentists (EN)",
        "queries": [
            "dentist",
            "dental clinic",
            "dental practice",
            "orthodontist",
            "dental implants",
            "oral surgeon",
        ],
    },
    "legal_en": {
        "name": "Lawyers (EN)",
        "queries": [
            "lawyer",
            "law firm",
            "attorney",
            "solicitor",
            "legal services",
            "notary",
        ],
    },
    "accounting_en": {
        "name": "Accountants (EN)",
        "queries": [
            "accountant",
            "accounting firm",
            "tax advisor",
            "bookkeeper",
            "CPA",
            "financial advisor",
        ],
    },
    "real_estate_en": {
        "name": "Real Estate (EN)",
        "queries": [
            "real estate agent",
            "real estate agency",
            "property management",
            "estate agent",
            "realtor",
            "property valuation",
        ],
    },
    "restaurant_en": {
        "name": "Restaurants (EN)",
        "queries": [
            "restaurant",
            "cafe",
            "bistro",
            "pizzeria",
            "bakery",
            "bar",
            "fast food",
            "catering",
        ],
    },
    "auto_en": {
        "name": "Auto Repair (EN)",
        "queries": [
            "auto repair",
            "car mechanic",
            "car dealership",
            "tire shop",
            "auto body shop",
            "car wash",
            "oil change",
        ],
    },
    "plumber_en": {
        "name": "Plumbers (EN)",
        "queries": [
            "plumber",
            "plumbing service",
            "plumbing company",
            "drain cleaning",
            "water heater repair",
            "emergency plumber",
        ],
    },
    "electrician_en": {
        "name": "Electricians (EN)",
        "queries": [
            "electrician",
            "electrical contractor",
            "electrical service",
            "electrical repair",
            "commercial electrician",
        ],
    },
    "construction_en": {
        "name": "Construction (EN)",
        "queries": [
            "construction company",
            "general contractor",
            "roofing contractor",
            "home builder",
            "renovation company",
            "painting contractor",
            "flooring company",
            "landscaping company",
        ],
    },
    "marketing_en": {
        "name": "Marketing Agencies (EN)",
        "queries": [
            "marketing agency",
            "digital marketing agency",
            "SEO agency",
            "web design agency",
            "social media agency",
            "advertising agency",
            "branding agency",
            "PR agency",
        ],
    },
    "fitness_en": {
        "name": "Fitness & Gyms (EN)",
        "queries": [
            "gym",
            "fitness center",
            "yoga studio",
            "personal trainer",
            "CrossFit",
            "martial arts",
            "pilates studio",
        ],
    },
    "beauty_en": {
        "name": "Beauty & Wellness (EN)",
        "queries": [
            "beauty salon",
            "hair salon",
            "nail salon",
            "barber shop",
            "spa",
            "tattoo studio",
            "massage therapist",
        ],
    },
    "cleaning_en": {
        "name": "Cleaning Services (EN)",
        "queries": [
            "cleaning service",
            "commercial cleaning",
            "house cleaning",
            "carpet cleaning",
            "window cleaning",
            "janitorial service",
        ],
    },
    "it_en": {
        "name": "IT Services (EN)",
        "queries": [
            "IT services",
            "computer repair",
            "web developer",
            "IT consulting",
            "managed IT services",
            "software company",
            "IT support",
        ],
    },
}
